Repository SELab-2/Dwengo-3, pull requests merged in 2025-05, with the labels that each got.

#357 Chore: removed createdAt and updatedAt fields
  client/src/util/interfaces/learningPath.interfaces.ts
  server/swagger.json
  server/util/types/learningPath.types.ts
Labels: cleanup

#365 feat: removed google id to store in db
  server/routes/auth.routes.ts
  server/util/types/auth.types.ts
Labels: bug

#377 hotfix: google auth now checks on email if user exists
  server/routes/auth.routes.ts
Labels: bug

#328 Frontend/klasgroep discussies
  client/src/App.tsx
  client/src/api/api.routes.ts
  client/src/api/assignmentSubmission.ts
  client/src/api/discussion.ts
  client/src/components/CreateMessageCard.tsx
  client/src/components/DateTypography.tsx
  client/src/components/DiscussionCard.tsx
  client/src/components/DiscussionListCard.tsx
  client/src/components/StudentAssignmentsTable.tsx
  client/src/components/TeacherAssignmentsTable.tsx
  client/src/components/textfields/DateTextField.tsx
  client/src/components/textfields/FileTextField.tsx
  client/src/hooks/useAssignment.ts
  client/src/hooks/useAssignmentSubmission.ts
  client/src/hooks/useAuth.ts
  client/src/hooks/useDiscussion.ts
  client/src/hooks/useMessage.ts
  client/src/util/app.routes.ts
  client/src/util/locale/en.ts
  client/src/util/locale/fr.ts
  client/src/util/locale/nl.ts
  client/src/views/AssignmentCreatePage.tsx
  client/src/views/ClassAssignmentPage.tsx
  client/src/views/ClassAssignmentsPage.tsx
  client/src/views/ClassDashboardPage.tsx
  client/src/views/ClassDiscussionsPage.tsx
  client/src/views/ClassStudentDetails.tsx
  client/src/views/DiscussionCreatePage.tsx
  client/src/views/LearningPathPage.tsx
  client/src/views/ProfilePage.tsx
  server/domain/assignmentSubmission.domain.ts
  server/domain/discussion.domain.ts
  server/persistence/assignment.persistence.ts
  server/persistence/assignmentSubmission.persistence.ts
  server/persistence/class.persistence.ts
  server/persistence/discussion.persistence.ts
  server/persistence/group.persistence.ts
  server/persistence/student.persistence.ts
  server/persistence/teacher.persistence.ts
  server/routes/assignmentSubmission.routes.ts
  server/routes/auth.routes.ts
  server/routes/discussion.routes.ts
  server/util/cookie-checks/cookieChecks.util.ts
  server/util/selectInput/assignment.select.ts
  server/util/selectInput/select.ts
  server/util/types/assignmentSubmission.types.ts
  server/util/types/discussion.types.ts
  server/util/types/error.types.ts
  server/util/types/group.types.ts
  test/frontend/component/LoginForm.test.tsx
  test/persistence/deleteData.persistence.test.ts
  test/vitest.config.integration.local.ts
Labels: frontend

#386 Backend/link progress learningpath
  client/package-lock.json
  client/package.json
  client/src/api/api.routes.ts
  client/src/api/assignmentSubmission.ts
  client/src/api/group.ts
  client/src/api/learningObject.ts
  client/src/api/learningPathNode.ts
  client/src/components/ClassCard.tsx
  client/src/hooks/useGroup.ts
  client/src/util/interfaces/assignmentSubmission.interfaces.ts
  client/src/util/interfaces/group.interfaces.ts
  client/src/util/interfaces/learningObject.interfaces.ts
  client/src/views/LearningPathPage.tsx
  client/src/views/LearningThemePage.tsx
  db/prisma/migrations/20250518182758_progress_link/migration.sql
  db/prisma/schema.prisma
  server/app.ts
  server/domain/assignment.domain.ts
  server/domain/assignmentSubmission.domain.ts
  server/domain/class.domain.ts
  server/domain/group.domain.ts
  server/persistence/assignment.persistence.ts
  server/persistence/group.persistence.ts
  server/routes/group.routes.ts
  server/util/selectInput/assignment.select.ts
  server/util/selectInput/select.ts
  server/util/types/assignmentSubmission.types.ts
  server/util/types/error.types.ts
  server/util/types/group.types.ts
  test/apiCalls/learningObject.test.ts
  test/apiCalls/learningPathNode.test.ts
  test/domain/assignment.domain.test.ts
  test/persistence/assignment.persistence.test.ts
  test/persistence/testData.ts
Labels: backend, frontend

#422 Learningpath favorites
  client/src/api/api.routes.ts
  client/src/hooks/useFavorite.ts
  client/src/util/interfaces/favorite.interfaces.ts
  client/src/util/interfaces/group.interfaces.ts
  client/src/views/LearningPathPage.tsx
  server/domain/favorites.domain.ts
  server/persistence/favorites.persistence.ts
  server/routes/favorites.routes.ts
  server/routes/group.routes.ts
  server/util/selectInput/select.ts
  server/util/types/error.types.ts
  server/util/types/group.types.ts
Labels: backend, frontend

#412 Frontend/loginpage fix UI in login/register page
  client/src/components/ChooseRole.tsx
  client/src/components/GoogleButton.tsx
  client/src/components/GoogleLoginButton.tsx
  client/src/components/IsStudentSwitch.tsx
  client/src/components/LoginForm.tsx
  client/src/components/RegisterForm.tsx
  client/src/util/locale/en.ts
  client/src/util/locale/fr.ts
  client/src/util/locale/nl.ts
  client/src/views/LoginPage.tsx
  client/src/views/RegisterPage.tsx
Labels: frontend, cleanup

#437 fix: learningpath id optional in MyLearningPage favorites request
  server/util/types/favorites.types.ts
Labels: bug
